

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace AbsUserCenter.Core.Model
{   
    /// <summary>
    /// 实体-BPermission 
    /// </summary>
    public partial class BPermission
    {
        /// <summary>
        /// 
        /// </summary>
        public int PMS_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PMS_DESC { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> PMS_PMT_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int PMS_PARENT_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> PMS_SYS_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool PMS_DELETED_FLAG { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int PMS_ORDER_NUM { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PMS_CREATIONUID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public DateTime PMS_CREATION_DT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PMS_URL { get; set; }
 
    }
}

namespace AbsUserCenter.Core.Model
{   
    /// <summary>
    /// 实体-BRole 
    /// </summary>
    public partial class BRole
    {
        /// <summary>
        /// 
        /// </summary>
        public int ROL_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ROL_DESC { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ROL_MEMO { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int ROL_ORDER_NUM { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public bool ROL_DELETED_FLAG { get; set; }
        /// <summary>
        /// 部门ID(对应BDepartment表)
        /// </summary>
        public Nullable<int> ROL_DPT_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ROL_CREATIONUID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public DateTime ROL_CREATION_DT { get; set; }
 
    }
}

namespace AbsUserCenter.Core.Model
{   
    /// <summary>
    /// 实体-BSystem 
    /// </summary>
    public partial class BSystem
    {
        /// <summary>
        /// 
        /// </summary>
        public int SYS_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SYS_DESC { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int SYS_ORDER_NUM { get; set; }
        /// <summary>
        /// 系统是否启用（0.未启用/禁用；1.启用）
        /// </summary>
        public bool SYS_ENABLED_FLAG { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SYS_DOMAIN { get; set; }
 
    }
}

namespace AbsUserCenter.Core.Model
{   
    /// <summary>
    /// 实体-BUser 
    /// </summary>
    public partial class BUser
    {
        /// <summary>
        /// 
        /// </summary>
        public int USR_ID { get; set; }
        /// <summary>
        /// 登录名
        /// </summary>
        public string USR_LOGINNAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string USR_PASSWORD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string USR_NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string USR_EMAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string USR_BOSS_EMAIL { get; set; }
        /// <summary>
        /// 是否可用（1.可用；0.禁用）
        /// </summary>
        public bool USR_ACCESS_FLAG { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<DateTime> USR_LASTACTIVE_DT { get; set; }
        /// <summary>
        /// 是否在线（1.在线；0.离线；默认0）
        /// </summary>
        public bool USR_ONLINE_FLAG { get; set; }
        /// <summary>
        /// 角色ID(对应BRole表)
        /// </summary>
        public Nullable<int> USR_ROL_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string USR_CREATIONUID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public DateTime USR_CREATION_DT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string USR_WECHAT_OPENID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string USR_PHONE { get; set; }
 
    }
}

namespace AbsUserCenter.Core.Model
{   
    /// <summary>
    /// 实体-HUser 
    /// </summary>
    public partial class HUser
    {
        /// <summary>
        /// 
        /// </summary>
        public long HUR_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> HUR_USR_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<DateTime> HUR_DT { get; set; }
        /// <summary>
        /// 操作类型（1.添加用户；2.登录；3.退出；4.修改密码；5.禁用账号；启用账号；）
        /// </summary>
        public Nullable<byte> HUR_TYPE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HUR_IP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HUR_CREATIONUID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<DateTime> HUR_CREATION_DT { get; set; }
 
    }
}

